# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import vlviapb_pb2 as vlviapb__pb2


class VLVIAStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RecognizeStream = channel.stream_stream(
        '/vlviapb.VLVIA/RecognizeStream',
        request_serializer=vlviapb__pb2.AudioFrames.SerializeToString,
        response_deserializer=vlviapb__pb2.RecognizeUpdate.FromString,
        )


class VLVIAServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RecognizeStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VLVIAServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RecognizeStream': grpc.stream_stream_rpc_method_handler(
          servicer.RecognizeStream,
          request_deserializer=vlviapb__pb2.AudioFrames.FromString,
          response_serializer=vlviapb__pb2.RecognizeUpdate.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'vlviapb.VLVIA', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
