# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vlviapb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vlviapb.proto',
  package='vlviapb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rvlviapb.proto\x12\x07vlviapb\"\x1d\n\x0b\x41udioFrames\x12\x0e\n\x06\x66rames\x18\x01 \x01(\x0c\"V\n\x0fRecognizeUpdate\x12\r\n\x05shift\x18\x01 \x01(\x05\x12\r\n\x05words\x18\x02 \x03(\t\x12%\n\x07timeout\x18\x03 \x01(\x0e\x32\x14.vlviapb.TimeoutType*P\n\x0bTimeoutType\x12\x0e\n\nNO_TIMEOUT\x10\x00\x12\x14\n\x10NO_INPUT_TIMEOUT\x10\x01\x12\x1b\n\x17SPEECH_COMPLETE_TIMEOUT\x10\x02\x32P\n\x05VLVIA\x12G\n\x0fRecognizeStream\x12\x14.vlviapb.AudioFrames\x1a\x18.vlviapb.RecognizeUpdate\"\x00(\x01\x30\x01\x62\x06proto3')
)

_TIMEOUTTYPE = _descriptor.EnumDescriptor(
  name='TimeoutType',
  full_name='vlviapb.TimeoutType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_TIMEOUT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_INPUT_TIMEOUT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPEECH_COMPLETE_TIMEOUT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=145,
  serialized_end=225,
)
_sym_db.RegisterEnumDescriptor(_TIMEOUTTYPE)

TimeoutType = enum_type_wrapper.EnumTypeWrapper(_TIMEOUTTYPE)
NO_TIMEOUT = 0
NO_INPUT_TIMEOUT = 1
SPEECH_COMPLETE_TIMEOUT = 2



_AUDIOFRAMES = _descriptor.Descriptor(
  name='AudioFrames',
  full_name='vlviapb.AudioFrames',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='vlviapb.AudioFrames.frames', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=55,
)


_RECOGNIZEUPDATE = _descriptor.Descriptor(
  name='RecognizeUpdate',
  full_name='vlviapb.RecognizeUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shift', full_name='vlviapb.RecognizeUpdate.shift', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='words', full_name='vlviapb.RecognizeUpdate.words', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='vlviapb.RecognizeUpdate.timeout', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=143,
)

_RECOGNIZEUPDATE.fields_by_name['timeout'].enum_type = _TIMEOUTTYPE
DESCRIPTOR.message_types_by_name['AudioFrames'] = _AUDIOFRAMES
DESCRIPTOR.message_types_by_name['RecognizeUpdate'] = _RECOGNIZEUPDATE
DESCRIPTOR.enum_types_by_name['TimeoutType'] = _TIMEOUTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioFrames = _reflection.GeneratedProtocolMessageType('AudioFrames', (_message.Message,), dict(
  DESCRIPTOR = _AUDIOFRAMES,
  __module__ = 'vlviapb_pb2'
  # @@protoc_insertion_point(class_scope:vlviapb.AudioFrames)
  ))
_sym_db.RegisterMessage(AudioFrames)

RecognizeUpdate = _reflection.GeneratedProtocolMessageType('RecognizeUpdate', (_message.Message,), dict(
  DESCRIPTOR = _RECOGNIZEUPDATE,
  __module__ = 'vlviapb_pb2'
  # @@protoc_insertion_point(class_scope:vlviapb.RecognizeUpdate)
  ))
_sym_db.RegisterMessage(RecognizeUpdate)



_VLVIA = _descriptor.ServiceDescriptor(
  name='VLVIA',
  full_name='vlviapb.VLVIA',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=227,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeStream',
    full_name='vlviapb.VLVIA.RecognizeStream',
    index=0,
    containing_service=None,
    input_type=_AUDIOFRAMES,
    output_type=_RECOGNIZEUPDATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VLVIA)

DESCRIPTOR.services_by_name['VLVIA'] = _VLVIA

# @@protoc_insertion_point(module_scope)
